# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniature', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=128)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Type'),
        ),
    ]
